name:                iohk-interview-abyaly
version:             0.1.0.0
github:              "githubuser/iohk-interview-abyaly"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/iohk-interview-abyaly#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- bytestring
- time
- mwc-random
- distributed-process
- distributed-static
- rank1dynamic
- network-transport
- network-transport-tcp
- binary
- mtl
- optparse-generic

library:
  source-dirs: src
  default-extensions:
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - GADTs
    - RecordWildCards

executables:
  iohk-interview-abyaly-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions:  DeriveGeneric
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iohk-interview-abyaly

tests:
  iohk-interview-abyaly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iohk-interview-abyaly
